spring:
  application:
    name=crawlingEx

  autoconfigure:      # ?? ???? ????? ?? ? ??????? ?? ??? ??? ?? ?? ??
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
